services:
    mongo:
        image: mongo
        networks:
            - keywords-net
        container_name: keywords-mongo
        restart: always
        environment:
            MONGO_INITDB_DATABASE: data
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: pass
        ports:
            - 27017:27017

    # elastic:
    #     image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    #     container_name: keywords-elastic
    #     restart: always
    #     ports:
    #         - 9200:9200
    #         - 9300:9300
    #     environment:
    #         discovery.type: single-node

    mongo-express:
        image: mongo-express
        networks:
            - keywords-net
        container_name: keywords-mongo-express
        restart: always
        ports:
            - 8081:8081
        depends_on:
            - mongo
        environment:
            ME_CONFIG_MONGODB_SERVER: mongo
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: pass
            ME_CONFIG_OPTIONS_EDITORTHEME: ambiance

    keywords:
        build: .
        networks:
            - keywords-net
        container_name: keywords
        restart: always
        ports:
            - 3030:3030
        depends_on:
            - mongo-express
            # - elastic
        volumes:
            - .:/usr/app
        command: npm run dev
        # command: npm run start
        environment:
            KEYWORD_ATTRIBUTES: 'firstName,hobbies'

networks:
    keywords-net:
        external: true
